"""
Populates / refreshes the Supabase `iainmobiliaria_macro_economics` table
from the local JSON file generated by download_macro_economics.py.

Usage:
    python scripts/populate_macro_economics.py              # upsert from JSON
    python scripts/populate_macro_economics.py --clean      # delete all rows first, then upsert
    python scripts/populate_macro_economics.py --dry-run    # print what would be uploaded
"""

import argparse
import json
import sys
from pathlib import Path

from loguru import logger

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_DIR))

from config import (
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
    DATA_DIR,
)

try:
    from config import TABLE_MACRO_ECONOMICS
except ImportError:
    TABLE_MACRO_ECONOMICS = "iainmobiliaria_macro_economics"

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logger.remove()
logger.add(
    sys.stdout,
    format="<green>{time:HH:mm:ss}</green> | <level>{level:<8}</level> | <level>{message}</level>",
    level="INFO",
)

JSON_PATH = DATA_DIR / "macro_economics_by_state.json"


def load_json() -> dict:
    """Load the macro-economics JSON file and return the dict."""
    if not JSON_PATH.exists():
        logger.error(
            f"JSON no encontrado: {JSON_PATH}\n"
            "Ejecuta primero: python scripts/download_macro_economics.py"
        )
        sys.exit(1)

    with open(JSON_PATH, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    logger.info(f"Cargados {len(data)} estados desde {JSON_PATH}")
    return data


def upsert_to_supabase(data: dict, clean: bool = False) -> int:
    """Upsert rows to iainmobiliaria_macro_economics.

    Args:
        data: dict keyed by state name, values are row dicts.
        clean: if True, delete all rows before upserting.

    Returns:
        Number of rows upserted.
    """
    from supabase import create_client

    client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)
    table = TABLE_MACRO_ECONOMICS

    if clean:
        logger.warning(f"Limpiando tabla {table} ...")
        try:
            client.table(table).delete().neq("state", "__never_match__").execute()
            logger.success("Tabla limpiada.")
        except Exception as exc:
            logger.error(f"Error limpiando tabla: {exc}")

    rows = list(data.values())
    batch_size = 50
    upserted = 0

    for i in range(0, len(rows), batch_size):
        batch = rows[i : i + batch_size]
        try:
            client.table(table).upsert(batch, on_conflict="state").execute()
            upserted += len(batch)
            logger.info(f"  Upserted {upserted}/{len(rows)}")
        except Exception as exc:
            logger.error(f"  Error en batch {i}: {exc}")

    return upserted


def dry_run(data: dict) -> None:
    """Print what would be uploaded without touching Supabase."""
    logger.info("=== DRY RUN — no se escribirá en Supabase ===")
    for state, record in data.items():
        indicators = {
            k: v
            for k, v in record.items()
            if k not in ("state", "data_vintage", "updated_at")
        }
        non_null = sum(1 for v in indicators.values() if v is not None)
        logger.info(f"  {state:<25} — {non_null}/{len(indicators)} indicadores")
    logger.info(f"Total: {len(data)} estados listos para upsert.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Populate iainmobiliaria_macro_economics from local JSON."
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Delete all rows before upserting.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be uploaded; do not touch Supabase.",
    )
    args = parser.parse_args()

    logger.info("=" * 60)
    logger.info("POPULATE MACRO ECONOMICS — Supabase")
    logger.info("=" * 60)

    data = load_json()

    if args.dry_run:
        dry_run(data)
        return

    upserted = upsert_to_supabase(data, clean=args.clean)

    logger.info("-" * 60)
    logger.success(
        f"Completado: {upserted}/{len(data)} estados upserted en {TABLE_MACRO_ECONOMICS}"
    )
    logger.info("-" * 60)


if __name__ == "__main__":
    main()
